"""add RESTRICT delete to products

Revision ID: 46f81df0b755
Revises: 85cf101c8fbf
Create Date: 2026-07-31 12:29:41.343787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f81df0b755'
down_revision: Union[str, Sequence[str], None] = '85cf101c8fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_search_vector'), table_name='products', postgresql_using='gin')
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'])
    op.create_index(op.f('ix_products_search_vector'), 'products', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
