"""add stripe_session_id to orders

Revision ID: 5e38aefef64b
Revises: 3361d7afa58e
Create Date: 2026-08-26 21:53:02.955249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e38aefef64b'
down_revision: Union[str, Sequence[str], None] = '3361d7afa58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('stripe_session_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'stripe_session_id')
    # ### end Alembic commands ###
