"""add slug field to products & categories, add cancellation reason to orders

Revision ID: c47ff2daf174
Revises: e413139e7347
Create Date: 2026-07-29 15:01:56.861141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47ff2daf174'
down_revision: Union[str, Sequence[str], None] = 'e413139e7347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(length=160), nullable=False))
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.add_column('orders', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('slug', sa.String(length=160), nullable=False))
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_column('products', 'slug')
    op.drop_column('orders', 'cancellation_reason')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
