from .categories import router as categories_router
from .products import router as products_router
from .product_variants import router as variant_router
from .auth import router as auth_router
from .users import router as users_router
from .carts import router as carts_router
from .discounts import router as discounts_router
from .addresses import router as addresses_router
from .orders import router as orders_router
from .payments import router as payment_router